import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = existsSync(join(root, 'web'))
  ? join(root, 'web')
  : join(root, '..', 'public', 'inner-shelter');
const dest = join(root, 'www');

mkdirSync(dest, { recursive: true });

for (const file of ['index.html', 'styles.css', 'app.js', 'config.js', 'manifest.json', 'sw.js', 'icon.svg', 'privacy.html']) {
  cpSync(join(src, file), join(dest, file));
}

const configPath = join(dest, 'config.js');
const exampleApi = join(root, 'config.example.js');
let apiUrl = '';

function readApiUrl(filePath) {
  const lines = readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//')) continue;
    const m = trimmed.match(/INNER_SHELTER_API\s*=\s*['"]([^'"]*)['"]/);
    if (m) return m[1];
  }
  return '';
}

if (existsSync(join(root, 'config.local.js'))) {
  apiUrl = readApiUrl(join(root, 'config.local.js'));
} else if (existsSync(exampleApi)) {
  apiUrl = readApiUrl(exampleApi);
}

writeFileSync(
  configPath,
  `// Auto-generated by scripts/sync-www.mjs — edit config.local.js then re-run npm run sync\nwindow.INNER_SHELTER_API = '${apiUrl}';\n`
);

console.log('Synced www/ from', src.includes('/web') ? 'web/' : 'public/inner-shelter');
console.log('API base:', apiUrl || '(same-origin — set config.local.js for iOS)');
