import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = existsSync(join(root, 'web'))
  ? join(root, 'web')
  : join(root, '..', 'public', 'inner-shelter');
const files = ['index.html', 'styles.css', 'app.js', 'config.js', 'manifest.json', 'sw.js', 'icon.svg', 'privacy.html'];
const audioSrc = join(src, 'audio', 'breath');

function readApiUrl(filePath) {
  const lines = readFileSync(filePath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('//')) continue;
    const m = trimmed.match(/INNER_SHELTER_API\s*=\s*['"]([^'"]*)['"]/);
    if (m) return m[1];
  }
  return '';
}

let apiUrl = '';
if (process.env.VERCEL) {
  apiUrl = '';
} else if (existsSync(join(root, 'config.local.js'))) {
  apiUrl = readApiUrl(join(root, 'config.local.js'));
} else if (existsSync(join(root, 'config.example.js'))) {
  apiUrl = readApiUrl(join(root, 'config.example.js'));
}

const configJs = `// Auto-generated by scripts/sync-www.mjs\nwindow.INNER_SHELTER_API = '${apiUrl}';\n`;

function sanitizeIndexForApp(html) {
  return html
    .replace(/<base href="[^"]*">\n?/g, '')
    .replace(/<link rel="stylesheet" href="\/portal-back\.css">\n?/g, '')
    .replace(/<a class="portal-back-link[^"]*"[^>]*>[^<]*<\/a>\n*/g, '');
}

for (const destName of ['www', 'public']) {
  const dest = join(root, destName);
  mkdirSync(dest, { recursive: true });
  for (const file of files) {
    if (file === 'config.js') {
      writeFileSync(join(dest, 'config.js'), configJs);
    } else if (file === 'index.html') {
      const html = readFileSync(join(src, 'index.html'), 'utf8');
      writeFileSync(join(dest, 'index.html'), sanitizeIndexForApp(html));
    } else {
      cpSync(join(src, file), join(dest, file));
    }
  }
  if (existsSync(audioSrc)) {
    cpSync(audioSrc, join(dest, 'audio', 'breath'), { recursive: true });
  }
}

console.log('Synced www/ + public/ from', src.includes('/web') ? 'web/' : 'public/inner-shelter');
console.log('API base:', apiUrl || '(same-origin)');
